import { test, expect } from '../fixtures/app.fixture'

test('AC-ADD/DELETE-BOOK: librarian adds and removes a book from the catalog', async ({ page, authPage }) => {
  await authPage.openLogin()
  await authPage.login(process.env.LIBRARIAN_EMAIL ?? 'librarian@example.com', process.env.LIBRARIAN_PASSWORD ?? 'Library123!')
  await page.getByRole('link', { name: 'จัดการหนังสือ' }).click()
  await page.getByLabel('ชื่อหนังสือ').fill('Clean Architecture')
  await page.getByLabel('ผู้แต่ง').fill('Robert C. Martin')
  await page.getByLabel('หมวดหมู่').fill('Software Engineering')
  await page.getByLabel('ISBN').fill('9780134494166')
  await page.getByRole('button', { name: 'เพิ่มหนังสือเข้าคลัง' }).click()
  await expect(page.getByRole('status')).toContainText('สำเร็จ')
  await page.getByRole('link', { name: 'ค้นหาหนังสือ' }).click()
  await expect(page.getByRole('heading', { name: 'Clean Architecture', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'จัดการหนังสือ' }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('row', { name: /Clean Architecture/ }).getByRole('button', { name: 'ลบ' }).click()
  await expect(page.getByRole('status')).toContainText('ลบ “Clean Architecture” ออกจากคลังสำเร็จ')
  await page.getByRole('link', { name: 'ค้นหาหนังสือ' }).click()
  await expect(page.getByRole('heading', { name: 'Clean Architecture', exact: true })).toHaveCount(0)
})
